# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d3ca5fdddc6fc05fe75d08c8e27ee89a6d1028a9a2543892fbb14ad9224f25c187f40da596ef82edf7db822448e92cf260f471275f4f2d95972ef04ea86953c

test:
  secret_key_base: f07169d6a698a6b6c799f7064a6cc8c0a17c20e357317597902ddd7650b041f0ee43ce8348386e709941cf60ac3a73e5d6e096bb95626f97de8b3bdf938eada4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
